#
# This software is contributed or developed by KYOCERA Corporation.
# (C) 2011 KYOCERA Corporation
#
# Makefile for the Linux IrDA infrared device drivers.
#
# 20 March 2015, 

obj-y			+= irdasd.o

irdasd-objs		:= irda_sd.o
