# This software is contributed or developed by KYOCERA Corporation.
# (C) 2019 KYOCERA Corporation
#

obj-$(CONFIG_OEM_HKADC)		+= oem-hkadc.o
obj-$(CONFIG_OEM_HKADC_USB_TM)		+= oem-hkadc_usb_tm.o
obj-$(CONFIG_OEM_HKADC_USB_TM_DET)		+= oem-hkadc_usb_tm_det.o
